### ISSUE TITLE
OutOfMemoryError  

### ISSUE THREAD

**Issue by yanbin92** [markzhai/AndroidPerformanceMonitor#109]
08-21 08:44:03.629 3161-5409/com.armboard.aierbon.activity E/BlockInfoEx: newInstance: 
                                                                          java.lang.OutOfMemoryError
                                                                              at java.io.BufferedReader.<init>(BufferedReader.java:97)
                                                                              at java.io.BufferedReader.<init>(BufferedReader.java:80)
                                                                              at com.github.moduth.blockcanary.ui.BlockInfoEx.newInstance(BlockInfoEx.java:33)
                                                                              at com.github.moduth.blockcanary.ui.DisplayActivity$LoadBlocks.run(DisplayActivity.java:404)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                              at java.lang.Thread.run(Thread.java:856)
08-21 08:44:03.679 3161-5409/com.armboard.aierbon.activity E/DisplayActivity: Could not read block log file, deleted :/mnt/sdcard/blockcanary/looper-2017-08-20_00-16-49.014.log
                                                                              com.github.moduth.blockcanary.ui.BlockInfoCorruptException: BlockInfo (looper-2017-08-20_00-16-49.014.log) is corrupt.
                                                                                  at com.github.moduth.blockcanary.ui.DisplayActivity$LoadBlocks.run(DisplayActivity.java:406)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                                  at java.lang.Thread.run(Thread.java:856)

**Comment by gosailing** [comment]
同问
