### ISSUE TITLE
Log路径生成失败

### ISSUE THREAD

**Issue by LitterSun** [markzhai/AndroidPerformanceMonitor#119]
设备：nexus 6
版本：Android 7.1.1
blockcanary版本：1.5.0

堆栈信息如下：
ava.io.FileNotFoundException: /data/storage/emulated/0/Android/data/com.test.testapm/cache/looper-2018-07-06_17-09-29.376.log (No such file or directory)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:140)
        at com.github.moduth.blockcanary.LogWriter.save(LogWriter.java:108)
        at com.github.moduth.blockcanary.LogWriter.save(LogWriter.java:56)
        at com.github.moduth.blockcanary.BlockCanaryInternals$1.onBlockEvent(BlockCanaryInternals.java:63)
        at com.github.moduth.blockcanary.LooperMonitor$1.run(LooperMonitor.java:80)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)

发现BlockCanaryInternals#getPath方法中，最后在目录前面加上了Data目录，导致目录生成失败。

**Comment by dingbuoyi** [comment]
解决方案？
