### ISSUE TITLE
CpuSampler报错

### ISSUE THREAD

**Issue by s949492225** [markzhai/AndroidPerformanceMonitor#122]
09-06 16:22:38.457 4007-4116/com.lrlz.beautyshop E/CpuSampler: doSample: 
    java.io.FileNotFoundException: /proc/stat (Permission denied)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:200)
        at java.io.FileInputStream.<init>(FileInputStream.java:150)
        at java.io.FileInputStream.<init>(FileInputStream.java:103)
        at com.github.moduth.blockcanary.CpuSampler.doSample(CpuSampler.java:108)
        at com.github.moduth.blockcanary.AbstractSampler$1.run(AbstractSampler.java:33)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)

android 8.0上必现
希望能够视频安卓8.0
谢谢

**Comment by conncui** [comment]
Android >= 26 就不允许第三方应用读取这个接口了。
https://issuetracker.google.com/issues/37140047#comment2
