### ISSUE TITLE
/proc/stat (Permission denied)

### ISSUE THREAD

**Issue by crazyounger** [markzhai/AndroidPerformanceMonitor#132]
Android 系统 9.0
报错：
java.io.FileNotFoundException: /proc/stat (Permission denied)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:231)
        at java.io.FileInputStream.<init>(FileInputStream.java:165)
        at java.io.FileInputStream.<init>(FileInputStream.java:112)
        at com.github.moduth.blockcanary.CpuSampler.doSample(CpuSampler.java:108)
        at com.github.moduth.blockcanary.AbstractSampler$1.run(AbstractSampler.java:33)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by BzCoder** [comment]
8.0以上已经被禁用，需要自己重新适配

**Comment by slo-w** [comment]
有没有解决办法 ？怎么适配

**Comment by BzCoder** [comment]
> 有没有解决办法 ？怎么适配

我自己改了一版适配了，你有兴趣试用下么？
implementation 'com.github.bzcoder:blockcanarycompat-android:0.0.1'
implementation 'com.github.bzcoder:blockcanarycompat-android-no-op:0.0.1'
