### ISSUE TITLE
android12崩溃，PendingIntent标志位需要适配

### ISSUE THREAD

**Issue by suyxin** [markzhai/AndroidPerformanceMonitor#147]
java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:378)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:461)
        at android.app.PendingIntent.getActivity(PendingIntent.java:447)
        at android.app.PendingIntent.getActivity(PendingIntent.java:411)
        at com.github.moduth.blockcanary.DisplayService.onBlock(DisplayService.java:46)
        at com.github.moduth.blockcanary.BlockCanaryInternals$1.onBlockEvent(BlockCanaryInternals.java:67)
        at com.github.moduth.blockcanary.LooperMonitor$1.run(LooperMonitor.java:80)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by suyxin** [comment]
PendingIntent pendingIntent = PendingIntent.getActivity(context, 1, intent, FLAG_UPDATE_CURRENT);
需要适配为

**Comment by suyxin** [comment]
PendingIntent pendingIntent = PendingIntent.getActivity(context, 1, intent, FLAG_IMMUTABLE | FLAG_UPDATE_CURRENT);

**Comment by sunmTree** [comment]
作者不更新了吗

**Comment by ideav5** [comment]
您发给我的信件已经收到。
谢谢!

**Comment by Jsonjia** [comment]
+1

**Comment by ideav5** [comment]
您发给我的信件已经收到。
谢谢!

**Comment by uidq1290** [comment]
已收到

**Comment by mhz-tiantian** [comment]
+1 一样的问题

**Comment by remigriffithqlip** [comment]
Ensure to specify either `FLAG_IMMUTABLE` or `FLAG_MUTABLE` when creating your PendingIntent to comply with Android 12 requirements.
