### ISSUE TITLE
NullPointerException when tested with Monkey

### ISSUE THREAD

**Issue by fengzee-me** [markzhai/AndroidPerformanceMonitor#54]
```
FATAL EXCEPTION: main
Process: com.xxxx.xxx, PID: 26457
java.lang.RuntimeException: Unable to stop activity {com.xxxx.xxx/com.github.moduth.blockcanary.ui.DisplayBlockActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.internal.view.menu.MenuBuilder.close()' on a null object reference
    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3359)
    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3405)
    at android.app.ActivityThread.access$1200(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1322)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5238)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.internal.view.menu.MenuBuilder.close()' on a null object reference
    at android.widget.ActionMenuPresenter$OverflowPopup.onDismiss(ActionMenuPresenter.java:685)
    at android.widget.PopupWindow.dismiss(PopupWindow.java:1364)
    at android.widget.ListPopupWindow.dismiss(ListPopupWindow.java:656)
    at com.android.internal.view.menu.MenuPopupHelper.dismiss(MenuPopupHelper.java:157)
    at android.widget.ActionMenuPresenter.hideOverflowMenu(ActionMenuPresenter.java:332)
    at android.widget.ActionMenuPresenter.dismissPopupMenus(ActionMenuPresenter.java:343)
    at android.widget.ActionMenuView.dismissPopupMenus(ActionMenuView.java:679)
    at android.widget.Toolbar.dismissPopupMenus(Toolbar.java:391)
    at com.android.internal.widget.ToolbarWidgetWrapper.dismissPopupMenus(ToolbarWidgetWrapper.java:394)
    at com.android.internal.widget.ActionBarOverlayLayout.dismissPopups(ActionBarOverlayLayout.java:810)
    at com.android.internal.policy.impl.PhoneWindow.checkCloseActionMenu(PhoneWindow.java:860)
    at com.android.internal.policy.impl.PhoneWindow.closePanel(PhoneWindow.java:815)
    at com.android.internal.policy.impl.PhoneWindow.closeAllPanels(PhoneWindow.java:1025)
    at android.app.Activity.performStop(Activity.java:6083)
    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3356)
    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3405) 
    at android.app.ActivityThread.access$1200(ActivityThread.java:144) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1322) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:135) 
    at android.app.ActivityThread.main(ActivityThread.java:5238) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
```

**Comment by markzhai** [comment]
没有有效堆栈，认为是无效bug
