### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by jp1017** [markzhai/AndroidPerformanceMonitor#67]
```
java.lang.NullPointerException
at com.github.moduth.blockcanary.ui.DisplayBlockActivity.getBlock(DisplayBlockActivity.java:311)
at com.github.moduth.blockcanary.ui.DisplayBlockActivity.updateUi(DisplayBlockActivity.java:216)
at com.github.moduth.blockcanary.ui.DisplayBlockActivity.access$400(DisplayBlockActivity.java:64)
at com.github.moduth.blockcanary.ui.DisplayBlockActivity$LoadBlocks$2.run(DisplayBlockActivity.java:416)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5017)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by markzhai** [comment]
@jp1017 seems not the newest version, there is not `DisplayBlockActivity` now

**Comment by jp1017** [comment]
刚升级到1.3.1：

` ``
compile 'com.github.markzhai:blockcanary-android:1.3.1'
```

还是报错：

```
java.lang.ExceptionInInitializerError
at com.github.moduth.blockcanary.ui.DisplayActivity$LoadBlocks.run(DisplayActivity.java:391)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NullPointerException
at java.util.LinkedList.addAll(LinkedList.java:386)
at com.github.moduth.blockcanary.ui.BlockCanaryUtils.<clinit>(BlockCanaryUtils.java:20)
at com.github.moduth.blockcanary.ui.DisplayActivity$LoadBlocks.run(DisplayActivity.java:391) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
at java.lang.Thread.run(Thread.java:841) 
```

**Comment by markzhai** [comment]
@jp1017 是不是没有打开app，直接打开了blocks那个入口？context 没有初始化，所以会空指针

**Comment by jp1017** [comment]
app　是运行的，之前可以的，前几天就报这个异常，郁闷

**Comment by markzhai** [comment]
@jp1017 能不能看下是什么东西空指针了？是不是更新到了新版，没有指定 concernPackages

**Comment by jp1017** [comment]
return null;

**Comment by jp1017** [comment]
@markzhai 设置后好了，直接复制你readme内容，没仔细看说明，导致悲剧，谢谢。

😄 👍 👋
