### ISSUE TITLE
空指针啊

### ISSUE THREAD

**Issue by zhoujianhanyu** [markzhai/AndroidPerformanceMonitor#71]
Thread-1591 1591 thread.name pool-17-thread-1, thread.id 1587, uncaughtException.
                                                                              java.lang.ExceptionInInitializerError
                                                                                  at com.github.moduth.blockcanary.ui.BlockCanaryUtils.isBlockInfoValid(BlockCanaryUtils.java)
                                                                                  at com.github.moduth.blockcanary.ui.DisplayActivity$LoadBlocks.run(DisplayActivity.java:391)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                  at java.lang.Thread.run(Thread.java:818)
                                                                               Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Collection.size()' on a null object reference
                                                                                  at java.util.LinkedList.addAll(LinkedList.java:386)
                                                                                  at com.github.moduth.blockcanary.ui.BlockCanaryUtils.<clinit>(BlockCanaryUtils.java:20)
                                                                                  at com.github.moduth.blockcanary.ui.BlockCanaryUtils.isBlockInfoValid(BlockCanaryUtils.java) 
                                                                                  at com.github.moduth.blockcanary.ui.DisplayActivity$LoadBlocks.run(DisplayActivity.java:391) 
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                  at java.lang.Thread.run(Thread.java:818)

**Comment by markzhai** [comment]
自己的App打开了吗？请描述情况

**Comment by markzhai** [comment]
@zhoujianhanyu 看一下 https://github.com/markzhai/AndroidPerformanceMonitor/issues/67

**Comment by zhoujianhanyu** [comment]
@markzhai 我的App开着的，点击通知栏就空指针。

**Comment by markzhai** [comment]
@zhoujianhanyu 看下 https://github.com/markzhai/AndroidPerformanceMonitor/issues/67，应该是使用错误

**Comment by zhoujianhanyu** [comment]
@markzhai 刚看了一下源码，是我没覆写 concernPackages这个方法的原因。

**Comment by etby** [comment]
=-= 我这边也空指针了, 不是可以为null吗? 为什么不覆写还会出问题. (希望能够只install start之后就可以使用)

**Comment by markzhai** [comment]
@etby 
是实现上的 bug，这两天会发一个版本修复

**Comment by etby** [comment]
@markzhai 感谢菊苣的开源精神 _(:зゝ∠)_ ( 渣渣也就只能提提Issue了

**Comment by markzhai** [comment]
改好发布了，见 1.4.0
