### ISSUE TITLE
配置了tinker  收到Notification 但是 没有detail信息

### ISSUE THREAD

**Issue by happywilma** [markzhai/AndroidPerformanceMonitor#92]

**Comment by markzhai** [comment]
@happywilma 是不是没有写那个文件夹的权限

**Comment by happywilma** [comment]
thank you, 的确是写权限问题

**Comment by TaitYoung** [comment]
@happywilma @markzhai 我也遇到了。请问是哪个权限呢？ App对应的storage权限已经授予了。

**Comment by TaitYoung** [comment]
![image](https://user-images.githubusercontent.com/6091057/28994646-e0254ac4-7a05-11e7-8cc9-45e709a7b7a9.png)
文件生成了，通知栏也有，但是点进去就没有详细信息。

**Comment by dazeGitHub** [comment]
我的也是，报错信息如下：
06-15 14:33:11.921 26375-26397/com.example.daze.testanr E/BlockInfo: newInstance: 
    java.lang.SecurityException: getDeviceId: Neither user 10204 nor current process has android.permission.READ_PHONE_STATE.
        at android.os.Parcel.readException(Parcel.java:1684)
        at android.os.Parcel.readException(Parcel.java:1637)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:4611)
        at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:851)
        at com.github.moduth.blockcanary.internal.BlockInfo.<clinit>(BlockInfo.java:114)
        at com.github.moduth.blockcanary.StackSampler.getThreadStackEntries(StackSampler.java:49)
        at com.github.moduth.blockcanary.BlockCanaryInternals$1.onBlockEvent(BlockCanaryInternals.java:55)
        at com.github.moduth.blockcanary.LooperMonitor$1.run(LooperMonitor.java:80)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.os.HandlerThread.run(HandlerThread.java:61)
06-15 14:33:11.939 26375-26397/com.example.daze.testanr E/LogWriter: save: 
    java.io.FileNotFoundException: /data/blockcanary/looper-2018-06-15_14-33-11.939.log (No such file or directory)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:140)
        at com.github.moduth.blockcanary.LogWriter.save(LogWriter.java:108)
        at com.github.moduth.blockcanary.LogWriter.save(LogWriter.java:56)
        at com.github.moduth.blockcanary.BlockCanaryInternals$1.onBlockEvent(BlockCanaryInternals.java:63)
        at com.github.moduth.blockcanary.LooperMonitor$1.run(LooperMonitor.java:80)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by dazeGitHub** [comment]
是权限问题，得适配 sdcard 读写权限
